@Address = http://localhost:5179

GET {{Address}}/myip/
X-API-Key: 6e1e2813b3cda938ed1df71cd7389f64355f948fce92a2dd525f90c3f3fd6e41
###

GET {{Address}}/myip/
###

GET {{Address}}/myip/
X-API-Key: 132
